package Vista;


import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;

import Controller.ControllerCRUD;
import Recursos.Usuario;

import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.FlowLayout;
import javax.swing.JButton;
import javax.swing.JTextField;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.awt.event.ActionEvent;
import javax.swing.JScrollPane;
import javax.swing.JComboBox;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luis
 */
public class PanelCRUD extends javax.swing.JPanel {

    private ControllerCRUD controller;
    private JComboBox cmBoxClientes;
    
    public PanelCRUD() {
        initComponents();
        this.inicializarPanel();
        
        ControllerCRUD.cargarTabla(tablaVehiculos);
        setLayout(null);
        add(btnNewButton);
        add(jScrollPane1);
        add(jLabel1);
        add(jLabel2);
        add(jLabelMatricula);
        add(txtModelo);
        add(txtMarca);
        add(txtMatricula);
        add(btRegistrar);
        
        JLabel lblNewLabel = new JLabel("Nombre:");
        lblNewLabel.setBounds(430, 144, 46, 14);
        add(lblNewLabel);
        
        txtNombre = new JTextField();
        txtNombre.setBounds(430, 169, 86, 20);
        add(txtNombre);
        txtNombre.setColumns(10);
        
        lblNewLabel_1 = new JLabel("Apellido:");
        lblNewLabel_1.setBounds(430, 200, 46, 14);
        add(lblNewLabel_1);
        
        txtApellido = new JTextField();
        txtApellido.setBounds(430, 225, 86, 20);
        add(txtApellido);
        txtApellido.setColumns(10);
       
        
        JLabel lblNewLabel_2 = new JLabel("Usuarios:");
        lblNewLabel_2.setBounds(430, 289, 46, 14);
        add(lblNewLabel_2);
        
        cmBoxClientes = new JComboBox();
        cmBoxClientes.setBounds(430, 314, 111, 22);
        add(cmBoxClientes);
        
        JLabel lblNewLabel_3 = new JLabel("ID Usuario: ");
        lblNewLabel_3.setBounds(10, 119, 46, 14);
        add(lblNewLabel_3);
        
        txtIdUsuario = new JTextField();
        txtIdUsuario.setBounds(63, 114, 86, 20);
        add(txtIdUsuario);
        txtIdUsuario.setColumns(10);
        
        addComboBox();
        
    }

 
private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {										
 
	 // TODO add your handling code here:
 
}										
 
 
 
private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {										
 
	

  //  DAOVehiculoImpl.getInstance().insertarVehiculo(new Vehiculo(txtMatricula.getText(), ))

    ControllerCRUD.insertarVehiculo(this, tablaVehiculos);

 
 
 
}										
 
 
 
public javax.swing.JTextField getTxtMatricula() {
	return txtMatricula;
}



public void setTxtMatricula(javax.swing.JTextField txtMatricula) {
	this.txtMatricula = txtMatricula;
}



public javax.swing.JTextField getTxtMarca() {
	return txtMarca;
}



public void setTxtMarca(javax.swing.JTextField txtMarca) {
	this.txtMarca = txtMarca;
}



public javax.swing.JTextField getTxtModelo() {
	return txtModelo;
}



public void setTxtModelo(javax.swing.JTextField txtModelo) {
	this.txtModelo = txtModelo;
}


public javax.swing.JTextField getTxtIdUsuario() {
	return txtIdUsuario;
}



public void setIdUsuario(javax.swing.JTextField txtIdUsuario) {
	this.txtIdUsuario = txtIdUsuario;
}
 
private javax.swing.JButton btRegistrar;
 
private javax.swing.JLabel jLabel1;
 
private javax.swing.JLabel jLabel2;
 
private javax.swing.JLabel jLabelMatricula;
 
private javax.swing.JScrollPane jScrollPane1;
 
private javax.swing.JTable tablaVehiculos;
 
private javax.swing.JTextField txtMatricula;
 
private javax.swing.JTextField txtMarca;
 
private javax.swing.JTextField txtModelo;
private JButton btnNewButton;
private JTextField txtNombre;
private JLabel lblNewLabel_1;
private JTextField txtApellido;
private JTextField txtIdUsuario;
    /**
     * Creates new form PanelCRUD
     */
 

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


private void inicializarPanel() {
	
	 jLabel1 = new javax.swing.JLabel();
	 jLabel1.setBounds(10, 14, 29, 14);
 
	 jScrollPane1 = new javax.swing.JScrollPane();
	 jScrollPane1.setBounds(10, 171, 375, 181);
 
	 tablaVehiculos = new javax.swing.JTable();
 
	 txtMarca = new javax.swing.JTextField();
	 txtMarca.setBounds(63, 11, 196, 20);
 
	 txtModelo = new javax.swing.JTextField();
	 txtModelo.setBounds(63, 40, 210, 25);
 
	 jLabel2 = new javax.swing.JLabel();
	 jLabel2.setBounds(10, 45, 34, 14);
 
	 jLabelMatricula = new javax.swing.JLabel();
	 jLabelMatricula.setBounds(10, 79, 43, 14);
 
	 txtMatricula = new javax.swing.JTextField();
	 txtMatricula.setBounds(63, 76, 196, 20);
 
	 btRegistrar = new javax.swing.JButton();
	 btRegistrar.setBounds(430, 41, 77, 23);
 
	 
	 jLabel1.setText("Marca");
	 
 
	 tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
 
		 new Object [][] {
 
			 {null, null, null, null, null},
 
			 {null, null, null, null, null},
 
			 {null, null, null, null, null},
 
			 {null, null, null, null, null}
 
		 },
 
		 new String [] {
 
			 "Title 1", "Title 2", "Title 3", "Title 4", "Title 5" 
 
		 }
	 ));
 
	 jScrollPane1.setViewportView(tablaVehiculos);
 
	 txtMarca.setName("marca"); // NOI18N
 
	 txtModelo.setToolTipText("");
 
	 txtModelo.setName("modelo"); // NOI18N
 
	 txtModelo.addActionListener(new java.awt.event.ActionListener() {
 
		 public void actionPerformed(java.awt.event.ActionEvent evt) {
			 txtModeloActionPerformed(evt);
		 }
	 });
 
 
 
	 jLabel2.setText("Modelo");
 
 
 
	 jLabelMatricula.setText("Matrícula");
 
	 txtMatricula.setToolTipText("");
 
	 btRegistrar.setText("Registrar");
 
	 btRegistrar.setActionCommand("btRegistrar");
 
	 btRegistrar.setName("btRegistrar"); // NOI18N
 
	 btRegistrar.addActionListener(new java.awt.event.ActionListener() {
 
		 public void actionPerformed(java.awt.event.ActionEvent evt) {
 
			 btRegistrarActionPerformed(evt);
 
		 }
 
	 });
	 setLayout(null);
	 
	 btnNewButton = new JButton("Dar Alta Usuario");
	 btnNewButton.addActionListener(new ActionListener() {
	 	public void actionPerformed(ActionEvent e) {
	 		
	 		controller.insertarUsuario(txtNombre.getText(), txtApellido.getText());
	 		

	 		addComboBox();
	 		
	 	}
	 });
	 btnNewButton.setBounds(410, 110, 122, 23);
	 add(btnNewButton);

	 
 
}// </editor-fold>	


private void addComboBox() {
	cmBoxClientes.removeAllItems();
	
	List<Usuario> listaUsuarios = controller.obtenerUsuarios();
	
	List<String> nombreUsuarios = new ArrayList<String>();
	
	for (Usuario usuario: listaUsuarios) {
		nombreUsuarios.add(usuario.getNombre());
	}
	
    for (String nombre : nombreUsuarios) {
    	cmBoxClientes.addItem(nombre);
    }
}
}
